{
	"name": "Project Scrum Methodology",
	"version": "1.0", 
	"depends": [
		"project",
	],
	"author": "vitraining.com",
	"category": "Project",
	'website': 'http://www.vitraining.com',
	'images': ['static/description/images/header.jpg'],
	"summary": "Manage Project in SCRUM methodology",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/epic.xml",
		"view/feature.xml",
		"view/backlog.xml",
		"view/release.xml",
		"view/sprint.xml",
		"view/addon.xml",
		"view/project.xml",
		"view/task.xml",
		"data/cron.xml",
	],
	"installable": True,
	"auto_install": False,
    "application": True,
}